[tools]
rojo = "rojo-rbx/rojo@7.4.1"
wally = "UpliftGames/Wally@0.3.2"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
selene = "Kampfkarren/selene@0.26.1"
stylua = "johnnymorganz/stylua@0.20.0"
darklua = "seaofvoices/darklua@0.13.1"
luau-lsp = "johnnymorganz/luau-lsp@1.29.1"
